version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
  auth:
    build: ./AuthService/
    env_file:
      - ./.env
    ports:
      - '8081:8081'
  discovery:
    build: ./Discovery/
    env_file:
      - ./.env
    ports:
      - '6969:6969'
  cache_1:
    build: ./Cache/
    env_file:
      - ./.env
    ports:
      - '8079:8079'
  cache_2:
    build: ./Cache2/
    env_file:
      - ./.env
    ports:
      - '8078:8078'
  messaging:
    build: ./MessagingService
    env_file:
      - ./.env
    ports:
      - '8069:8069'
  spellchecker:
    build: ./SpellcheckerService
    env_file:
      - ./.env
    ports:
      - '8082:8082'
  spellchecker_2:
    build: ./SpellcheckerService2
    env_file:
      - ./.env
    ports:
      - '8083:8083'
  toxicity:
    build: ./ToxicityDetectionService
    env_file:
      - ./.env
    ports:
      - '8084:8084'
  toxicity_2:
    build: ./ToxicityDetectionService2
    env_file:
      - ./.env
    ports:
      - '8085:8085'
  gateway:
    build: ./Gateway/
    ports:
      - '8080:8080'
volumes:
  mongo:
